language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - sh -c "if [ '$PHPCS' = '1' ]; then composer require squizlabs/php_codesniffer; fi"

  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev phpunit/phpcov:~2.0; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=ruleset.xml ./src; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"

after_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/phpcov.php --merge --clover build/logs/clover.xml --whitelist ./src; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
