language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Fabricate
    - REQUIRE=""
    - DB=mysql CAKE_REF=2.4.10

  matrix:
    - DB=mysql CAKE_REF=2.4.10
    - DB=mysql CAKE_REF=2.5.9
    - DB=mysql CAKE_REF=2.6.13
    - DB=mysql CAKE_REF=2.7.11
    - DB=mysql CAKE_REF=2.8.9

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql
        - CAKE_VERSION=2.7
        - CODECOVERAGE=1
    - php: 5.4
      env:
        - PHPCS=1
        - PHPCS_ARGS="-p -s --extensions=php --standard=ruleset.xml --ignore='*/Test/*,*/Vendor/*' ."
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
  - rm composer.json
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
