language: php

dist: precise

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - PLUGIN_NAME=Fabricate
    - REQUIRE=""
    - DB=mysql CAKE_REF=2.4.10

  matrix:
    - DB=mysql CAKE_REF=2.10.16

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql
        - CAKE_VERSION=2.10
        - CODECOVERAGE=1
    - php: 5.4
      env:
        - PHPCS=1
        - PHPCS_ARGS="-p -s --extensions=php --standard=ruleset.xml --ignore='*/Test/*,*/Vendor/*' ."
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh
  - if [[ ${TRAVIS_PHP_VERSION:0:3} =~ ^7\.[23]$ ]] ; then composer global require 'phpunit/phpunit=5.7.26' ; fi

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
